plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\maxmi\\Documents\\Codex\\2026-06-06\\files-mentioned-by-the-user-renata\\work\\renata-github"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/kids-language-lessons.html"
to = "/escola.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/learn-portuguese.html"
to = "/adultos.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reviews.html"
to = "/sobre.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en/index.html"
to = "/en/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]